@Library('adrianblade-jenkins')

def baseImage = env.BASE_IMAGE ?: 'gradle'
def gitRef = env.GIT_REF ?: 'main'
def imageTag = env.IMAGE_TAG ?: 'latest'

quickstarterPipeline(
  imageStreamTag: "gradle:latest",
  compiler: "gradle",
  gitUrlHttp: "<"
) { context ->

  stage('Write something') {
      sh "echo hi!"
  }

  //compileProject(context)

}