def odsNamespace = env.ODS_NAMESPACE ?: 'ods'
def odsGitRef = env.ODS_GIT_REF ?: 'master'
def odsImageTag = env.ODS_IMAGE_TAG ?: 'latest'
library("adr-jenkins-shared-library@${odsGitRef}")

quickstarterPipeline(
  imageStreamTag: "${odsNamespace}/jenkins-agent-golang:${odsImageTag}",
  compiler: "gradle"
) { context ->

  stage('Write something') {
    dir(context.targetDir) {
      sh "echo hi!"
    }
  }

  compileProject(context)

}