@Library('adrianblade-jenkins')

def baseImage = env.BASE_IMAGE ?: 'gradle'
def gitRef = env.GIT_REF ?: 'main'
def imageTag = env.IMAGE_TAG ?: 'latest'

quickstarterPipeline(
  imageStreamTag: "gradle:latest",
  compiler: "gradle"
) { context ->

  stage('Write something') {
    dir(context.targetDir) {
      sh "echo hi!"
    }
  }

  //compileProject(context)

}